import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

const Mulishs = Mulish({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Mulishs.variable} antialiased`}>{children}</body>
    </html>
  );
}
